= Advanced connection information

include::{common-partial}/connect-advanced.adoc[tag=connection-uri]

include::{common-partial}/connect-advanced.adoc[tag=connection-protocols]


== Authentication methods


=== Basic authentication

The basic authentication scheme relies on traditional username and password.
These can either be the credentials for your local installation, or the ones provided with an Aura instance.

[source, go]
----
driver, err := neo4j.NewDriverWithContext(
    dbUri,
    neo4j.BasicAuth(dbUser, dbPassword, ""))
----

[INFO]
The basic authentication scheme can also be used to authenticate against an LDAP server (Enterprise Edition only).


=== Kerberos authentication

The Kerberos authentication scheme requires a base64-encoded ticket.
It can only be used if the server has the link:{neo4j-docs-base-uri}/kerberos-add-on/current/deployment/[Kerberos Add-on installed].

[source, go, test-skip]
----
driver, err := neo4j.NewDriverWithContext(dbUri, neo4j.KerberosAuth(ticket))
----


=== Bearer authentication

The bearer authentication scheme requires a base64-encoded token provided by an Identity Provider through Neo4j's link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/sso-integration[Single Sign-On feature].

[source, go, test-skip]
----
driver, err := neo4j.NewDriverWithContext(dbUri, neo4j.BearerAuth(token))
----

[NOTE]
The bearer authentication scheme requires link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/sso-integration[configuring Single Sign-On on the server].
Once configured, clients can discover Neo4j's configuration through the link:https://neo4j.com/docs/http-api/current/endpoints/#discovery-api[Discovery API].


=== Custom authentication

Use the function link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#CustomAuth[`CustomAuth`] to log into a server having a custom authentication scheme.


=== No authentication

Use the function link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j#NoAuth[`NoAuth`] to access a server where authentication is disabled.

[source, go, test-skip]
----
driver, err := neo4j.NewDriverWithContext(dbUri, neo4j.NoAuth())
----


[#mtls]
[role=label--new-5.27]
== Mutual TLS (client-side certificates as 2FA)

Mutual TLS (mTLS) allows you to use a client certificate as second factor for authenticating with the server.
The certificate can only be used together with an authentication token and is not a replacement of regular authentication, unless authentication is disabled on the server.

[.tabbed-example]
=====
[.include-with-static-certificate]
======
Use link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/auth#NewStaticClientCertificateProvider[`auth.NewStaticClientCertificateProvider()`] for static certificates. +
The method takes a link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/auth#ClientCertificate[`ClientCertificate`] instance.

[source, go, test-skip]
----
password := "theCertPassword"
certProvider, err := auth.NewStaticClientCertificateProvider(auth.ClientCertificate {
  CertFile: "path/to/cert.pem",
  KeyFile:  "path/to/key.pem",
  Password: &password,
})
if err != nil {
  log.Fatalf("Failed to load certificate: %v", err)
}
_, _ = neo4j.NewDriverWithContext(dbUri, neo4j.BasicAuth(dbUser, dbPassword, ""), func(config *config.Config) {
  config.ClientCertificateProvider = certProvider
})
----

======
[.include-with-rotating-certificate]
======

Use link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/auth#NewRotatingClientCertificateProvider[`auth.NewRotatingClientCertificateProvider()`] for rotating certificates. +
The method takes a link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/auth#ClientCertificate[`ClientCertificate`] instance.

[source, go, test-skip]
----
password := "theCertPassword"
certProvider, err := auth.NewRotatingClientCertificateProvider(auth.ClientCertificate {
  CertFile: "path/to/cert.pem",
  KeyFile:  "path/to/key.pem",
  Password: &password,
})
if err != nil {
  log.Fatalf("Failed to load certificate: %v", err)
}
_, _ = neo4j.NewDriverWithContext(dbUri, neo4j.BasicAuth(dbUser, dbPassword, ""), func(config *config.Config) {
  config.ClientCertificateProvider = certProvider
})

// use the driver a bit...

// when it's time to rotate the certificate...
err = provider.UpdateCertificate(auth.ClientCertificate {
  CertFile: "path/to/new_cert.pem",
  KeyFile:  "path/to/new_key.pem",
  Password: &password,
})
if err != nil {
  log.Fatalf("Failed to update certificate: %v", err)
}

// use the driver again...
----

======
=====


For more information, see link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/auth#ClientCertificateProvider[API docs -> `ClientCertificateProvider`].


== Custom address resolver

When creating a `DriverWithContext` object, you can specify a _resolver_ function to resolve the connection address the driver is initialized with.
Note that addresses that the driver receives in routing tables are not resolved with the custom resolver.
Your resolver function is called with a link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/config#ServerAddress[`ServerAddress`] object and should return a list of link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/config#ServerAddress[`ServerAddress`] objects.

.Connection to `example.com` on port `9999` is resolved to `localhost` on port `7687`
[source, go]
----
// import "github.com/neo4j/neo4j-go-driver/v5/neo4j/config"

driver, err := neo4j.NewDriverWithContext(
    "neo4j://example.com:9999", neo4j.BasicAuth(dbUser, dbPassword, ""),
    func(conf *config.Config) {
        conf.AddressResolver = func(address config.ServerAddress) []config.ServerAddress {
            return []config.ServerAddress{
                neo4j.NewServerAddress("localhost", "7687"),
            }
        }
})
defer driver.Close(ctx)
----


== Further connection parameters

You can find all `DriverWithContext` configuration parameters in the link:https://pkg.go.dev/github.com/neo4j/neo4j-go-driver/v5/neo4j/config#Config[API documentation -> config package].


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{common-partial}/glossary.adoc[]
include::../partials/glossary.adoc[]
endif::[]
